[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "datasense"
authors = [{name = "Gilles Pilon", email = "gillespilon13@gmail.com"}]
dynamic = ["version", "description"]
